package entities;

// Generated Jan 28, 2015 12:24:24 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Advice generated by hbm2java
 */
@Entity
@Table(name = "advice")
public class Advice implements java.io.Serializable {

	private Integer id;
	private Date receivingDate;
	private String code;
	private Set<ProductAdvice> productAdvices = new HashSet<ProductAdvice>(0);

	public Advice() {
	}

	public Advice(Date receivingDate, String code,
			Set<ProductAdvice> productAdvices) {
		this.receivingDate = receivingDate;
		this.code = code;
		this.productAdvices = productAdvices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "receiving_date", length = 10)
	public Date getReceivingDate() {
		return this.receivingDate;
	}

	public void setReceivingDate(Date receivingDate) {
		this.receivingDate = receivingDate;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "advice")
	public Set<ProductAdvice> getProductAdvices() {
		return this.productAdvices;
	}

	public void setProductAdvices(Set<ProductAdvice> productAdvices) {
		this.productAdvices = productAdvices;
	}

}
