package entities;

// Generated Jan 28, 2015 12:24:24 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NaturalId;

/**
 * Alarm generated by hbm2java
 */
@Entity
@Table(name = "alarm")
public class Alarm implements java.io.Serializable {

	private Integer id;
	private String code;
	private String description;
	private Date lastFiringDate;
	private AlarmTypeEnum type;
	private Product product;
	private Boolean active;
	private Set<User> users = new HashSet<User>(0);
	private Set<Role> roles = new HashSet<Role>(0);

	public Alarm() {
	}

	public Alarm(String description, Date lastFiringDate, AlarmTypeEnum type,
			Product product, Boolean active, String code, Set<User> users,
			Set<Role> roles) {
		this.description = description;
		this.lastFiringDate = lastFiringDate;
		this.type = type;
		this.active = active;
		this.code = code;
		this.users = users;
		this.roles = roles;
		this.setProduct(product);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_firing_date", length = 10)
	public Date getLastFiringDate() {
		return this.lastFiringDate;
	}

	public void setLastFiringDate(Date lastFiringDate) {
		this.lastFiringDate = lastFiringDate;
	}

	@Column(name = "type", length = 45)
	public AlarmTypeEnum getType() {
		return this.type;
	}

	public void setType(AlarmTypeEnum type) {
		this.type = type;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@NaturalId(mutable = false)
	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_alarms", joinColumns = { @JoinColumn(name = "alarm_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "role_alarms", joinColumns = { @JoinColumn(name = "alarm_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
