package entities;

// Generated Jan 28, 2015 12:24:24 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductAdviceId generated by hbm2java
 */
@Embeddable
public class ProductAdviceId implements java.io.Serializable {

	private int adviceId;
	private int productId;

	public ProductAdviceId() {
	}

	public ProductAdviceId(int adviceId, int productId) {
		this.adviceId = adviceId;
		this.productId = productId;
	}

	@Column(name = "advice_id", nullable = false)
	public int getAdviceId() {
		return this.adviceId;
	}

	public void setAdviceId(int adviceId) {
		this.adviceId = adviceId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductAdviceId))
			return false;
		ProductAdviceId castOther = (ProductAdviceId) other;

		return (this.getAdviceId() == castOther.getAdviceId())
				&& (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAdviceId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
