package entities;

// Generated Jan 28, 2015 12:24:24 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private Integer id;
	private String name;
	private String code;
	private Float weight;
	private String description;
	private Float unitPrice;
	private String unitOfMeasure;
	private String active;
	private Float threshold;
	private Set<ProductAdvice> productAdvices = new HashSet<ProductAdvice>(0);
	private Set<Inventory> inventories = new HashSet<Inventory>(0);
	private Set<ProductLine> productLines = new HashSet<ProductLine>(0);

	public Product() {
	}

	public Product(String name, String code, Float weight, String description,
			Float unitPrice, String unitOfMeasure, String active,
			Float threshold, Set<ProductAdvice> productAdvices,
			Set<Inventory> inventories, Set<ProductLine> productLines) {
		this.name = name;
		this.code = code;
		this.weight = weight;
		this.description = description;
		this.unitPrice = unitPrice;
		this.unitOfMeasure = unitOfMeasure;
		this.active = active;
		this.threshold = threshold;
		this.productAdvices = productAdvices;
		this.inventories = inventories;
		this.productLines = productLines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "weight", precision = 12, scale = 0)
	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "unit_price", precision = 12, scale = 0)
	public Float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "unit_of_measure", length = 45)
	public String getUnitOfMeasure() {
		return this.unitOfMeasure;
	}

	public void setUnitOfMeasure(String unitOfMeasure) {
		this.unitOfMeasure = unitOfMeasure;
	}

	@Column(name = "active", length = 45)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "threshold", precision = 12, scale = 0)
	public Float getThreshold() {
		return this.threshold;
	}

	public void setThreshold(Float threshold) {
		this.threshold = threshold;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductAdvice> getProductAdvices() {
		return this.productAdvices;
	}

	public void setProductAdvices(Set<ProductAdvice> productAdvices) {
		this.productAdvices = productAdvices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductLine> getProductLines() {
		return this.productLines;
	}

	public void setProductLines(Set<ProductLine> productLines) {
		this.productLines = productLines;
	}

}
