package entities;

// Generated Jan 28, 2015 12:24:24 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductLineId generated by hbm2java
 */
@Embeddable
public class ProductLineId implements java.io.Serializable {

	private int productId;
	private int orderId;

	public ProductLineId() {
	}

	public ProductLineId(int productId, int orderId) {
		this.productId = productId;
		this.orderId = orderId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductLineId))
			return false;
		ProductLineId castOther = (ProductLineId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getOrderId() == castOther.getOrderId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getOrderId();
		return result;
	}

}
