package entities;

// Generated Jan 28, 2015 12:24:24 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductAdvice generated by hbm2java
 */
@Entity
@Table(name = "product_advice")
public class ProductAdvice implements java.io.Serializable {

	private ProductAdviceId id;
	private Advice advice;
	private Product product;
	private Date expiryDate;
	private Float quantity;
	private String code;

	public ProductAdvice() {
	}

	public ProductAdvice(ProductAdviceId id, Advice advice, Product product) {
		this.id = id;
		this.advice = advice;
		this.product = product;
	}

	public ProductAdvice(ProductAdviceId id, Advice advice, Product product,
			Date expiryDate, Float quantity, String code) {
		this.id = id;
		this.advice = advice;
		this.product = product;
		this.expiryDate = expiryDate;
		this.quantity = quantity;
		this.code = code;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "adviceId", column = @Column(name = "advice_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)) })
	public ProductAdviceId getId() {
		return this.id;
	}

	public void setId(ProductAdviceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "advice_id", nullable = false, insertable = false, updatable = false)
	public Advice getAdvice() {
		return this.advice;
	}

	public void setAdvice(Advice advice) {
		this.advice = advice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiry_date", length = 10)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "quantity", precision = 12, scale = 0)
	public Float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
